#anigamerplus latest python build

name: aniGamerPlus Build Artifact

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy2 and pypy3
      matrix:
        python: [3.8, 3.9]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build package
      run: pyinstaller --noconfirm --onefile --console --icon %cd%\aniGamerPlus_0000.ico --clean --add-data %cd%;aniGamerPlus/  %cd%\aniGamerPlus.py
      shell: cmd
    - name: Upload math result for job 2
      uses: actions/upload-artifact@v2
      with:
       name: anigamer_artifacts
       path: aniGamerPlus.exe
