#anigamerplus latest python build

name: aniGamerPlus Build Artifact

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: windows-2019
    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy2 and pypy3
      matrix:
        python: [3.9.x, 3.10.x]
        builder: ["pyinstaller", "nuitka"]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with: 
          python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ${{ matrix.builder }}
    - name: Build exe - pyinstaller
      if:  ${{ matrix.builder == 'pyinstaller' }}
      run: pyinstaller --noconfirm --distpath %cd%\ --onefile --console --icon %cd%\Dashboard\static\img\aniGamerPlus.ico --clean %cd%\aniGamerPlus.py
      shell: cmd
    - name: Build exe - nuitka
      if:  ${{ matrix.builder == 'nuitka' }}
      run: nuitka --onefile --onefile-no-compression --standalone --assume-yes-for-downloads --windows-console-mode=force --windows-icon-from-ico=%cd%\Dashboard\static\img\aniGamerPlus.ico %cd%\aniGamerPlus.py
      shell: cmd
    - name: Upload exe
      uses: actions/upload-artifact@v4
      with:
       name: aniGamerPlus_artifacts_py_V${{ matrix.python }}_${{matrix.builder}}
       path: |
         aniGamerPlus.exe
         Dashboard/
         LICENSE
         README.md
         DanmuTemplate.ass
         sn_list-sample.txt
         config-sample.json
